### ISSUE TITLE
error displaying widget

### ISSUE THREAD

**Issue by zhwang0** [tylere/jupyterlab-ee#1]
ee package works but I cannot use ipywighets and ipyleaflet.
```
import ipywidgets
ipywidgets.IntSlider()
```
The error is "Error displaying widget". The same error occurs for ipyleaflet. 

From #https://github.com/maartenbreddels/ipyvolume/issues/102, I tried installing ipyvolumn using 
```
jupyter labextension install ipyvolumn
```
in the command kernel, but it failed: 

![image](https://user-images.githubusercontent.com/22181767/50672514-8319ba80-0fa6-11e9-8390-e7e5e4eae40d.png)

Does anyone know how to fix it? Thanks in advance for your help!

**Comment by tylere** [comment]
Given the number of Python packages that are required, I have moved toward publishing Docker stacks with versioned packages that work well together in the [gee-community/ee-jupyter-contrib](https://github.com/gee-community/ee-jupyter-contrib) repository.

Here is the latest [Dockerfile](https://github.com/gee-community/ee-jupyter-contrib/blob/master/docker/jupyter-scipy-notebook-ee/Dockerfile), that includes a step for installing ipyvolume.

Installing `ipyvolume` directly may work as well, but note that you had misspelled he package name (i.e. not "ipyvolum**n**")

Cheers,
Tyler

**Comment by zhwang0** [comment]
Thank you so much! The latest Dockerfile works. 

Best,
Zhihao
